use std::path::Path;

const VITE_CONFIG_TEMPLATE: &str = r#"// Generated by Saddle. Do not edit — regenerated on every project load.
import { defineConfig } from 'vite';
import saddlePlugin from './saddle-plugin.mjs';
__USER_CONFIG_IMPORT__

export default defineConfig(async (env) => {
  __USER_CONFIG_RESOLVE__
  return {
    ...config,
    plugins: [...(config.plugins ?? []), saddlePlugin()],
  };
});
"#;

const SADDLE_PLUGIN_TEMPLATE: &str = r#"// Generated by Saddle. Do not edit — regenerated on every project load.
const VIRTUAL_ID = 'virtual:saddle-bridge';
const RESOLVED_ID = '\0' + VIRTUAL_ID;
const BRIDGE_SOURCE = __BRIDGE_SOURCE__;

export default function saddlePlugin() {
  return {
    name: 'saddle',
    resolveId(id) { if (id === VIRTUAL_ID) return RESOLVED_ID; },
    load(id) { if (id === RESOLVED_ID) return BRIDGE_SOURCE; },
    transformIndexHtml(html) {
      return html.replace(
        /<\/head>/i,
        `<script type="module" src="/@id/${VIRTUAL_ID}"></script></head>`
      );
    },
  };
}
"#;

const BRIDGE_SOURCE: &str = include_str!("../../saddle-bridge.js");

pub fn write_saddle_runtime(project_root: &str, vite_config_path: Option<&str>) -> Result<(), String> {
    let root = Path::new(project_root);
    let saddle_dir = root.join(".saddle");
    std::fs::create_dir_all(&saddle_dir).map_err(|e| format!("create .saddle: {e}"))?;

    // Compute the two template fills based on whether we found a user config.
    let (user_config_import, user_config_resolve) = match vite_config_path {
        Some(p) => {
            // Canonicalise both root and the config path so symlinks (e.g. macOS /tmp → /private/tmp)
            // don't break the prefix strip.
            let canon_root = std::fs::canonicalize(root)
                .map_err(|e| format!("canonicalize root: {e}"))?;
            let canon_cfg = std::fs::canonicalize(p)
                .map_err(|e| format!("canonicalize vite config: {e}"))?;
            let rel = canon_cfg
                .strip_prefix(&canon_root)
                .map_err(|_| {
                    // Fallback: just use the file name. The two files live in the same dir
                    // so `../{filename}` will resolve correctly from .saddle/.
                    "vite config not under project root".to_string()
                })
                .map(|r| r.to_path_buf())
                .unwrap_or_else(|_| {
                    std::path::PathBuf::from(canon_cfg.file_name().unwrap_or_default())
                });
            let import_path = format!("../{}", rel.display());
            // Use serde_json so embedded quotes/backslashes/spaces don't break the JS string literal.
            let import_literal = serde_json::to_string(&import_path)
                .map_err(|e| format!("encode import path: {e}"))?;
            let import_line = format!("import userConfig from {import_literal};");
            let resolve_line =
                "const config = typeof userConfig === 'function' ? await userConfig(env) : userConfig;"
                    .to_string();
            (import_line, resolve_line)
        }
        None => {
            // No user config detected — generate a minimal wrapper. Honest about being empty.
            let import_line = String::new();
            let resolve_line = "const config = {};".to_string();
            (import_line, resolve_line)
        }
    };

    let vite_config_contents = VITE_CONFIG_TEMPLATE
        .replace("__USER_CONFIG_IMPORT__", &user_config_import)
        .replace("__USER_CONFIG_RESOLVE__", &user_config_resolve);
    std::fs::write(saddle_dir.join("vite.config.mts"), vite_config_contents)
        .map_err(|e| format!("write vite.config.mts: {e}"))?;

    // saddle-plugin.mjs: inline the bridge as a JSON string literal so escaping is correct.
    let bridge_literal = serde_json::to_string(BRIDGE_SOURCE).map_err(|e| format!("encode bridge: {e}"))?;
    let plugin_contents = SADDLE_PLUGIN_TEMPLATE.replace("__BRIDGE_SOURCE__", &bridge_literal);
    std::fs::write(saddle_dir.join("saddle-plugin.mjs"), plugin_contents)
        .map_err(|e| format!("write saddle-plugin.mjs: {e}"))?;

    // .gitignore: append `.saddle/` if not already present. Create file if missing.
    let gitignore = root.join(".gitignore");
    let current = std::fs::read_to_string(&gitignore).unwrap_or_default();
    if !current.lines().any(|l| {
        let trimmed = l.trim().trim_start_matches('/').trim_end_matches('/');
        trimmed == ".saddle"
    }) {
        let new_contents = if current.is_empty() {
            ".saddle/\n".to_string()
        } else if current.ends_with('\n') {
            format!("{current}.saddle/\n")
        } else {
            format!("{current}\n.saddle/\n")
        };
        std::fs::write(&gitignore, new_contents).map_err(|e| format!("write .gitignore: {e}"))?;
    }

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::TempDir;

    #[test]
    fn writes_saddle_dir_files() {
        let tmp = TempDir::new().unwrap();
        std::fs::write(tmp.path().join("vite.config.ts"), "export default {};").unwrap();

        write_saddle_runtime(
            tmp.path().to_str().unwrap(),
            Some(tmp.path().join("vite.config.ts").to_str().unwrap()),
        ).unwrap();

        let cfg = std::fs::read_to_string(tmp.path().join(".saddle/vite.config.mts")).unwrap();
        assert!(cfg.contains("../vite.config.ts"));
        assert!(!cfg.contains("__USER_CONFIG_IMPORT__"), "vite config template not fully substituted: {cfg}");
        assert!(!cfg.contains("__USER_CONFIG_RESOLVE__"), "vite config template not fully substituted: {cfg}");

        let plugin = std::fs::read_to_string(tmp.path().join(".saddle/saddle-plugin.mjs")).unwrap();
        assert!(plugin.contains("virtual:saddle-bridge"));
        // The bridge contents got inlined as a JSON string.
        assert!(plugin.contains("__SADDLE_BRIDGE_INSTALLED__"));
        assert!(!plugin.contains("__BRIDGE_SOURCE__"), "plugin template not fully substituted: {plugin}");
    }

    #[test]
    fn no_vite_config_writes_empty_wrapper() {
        let tmp = TempDir::new().unwrap();
        write_saddle_runtime(tmp.path().to_str().unwrap(), None).unwrap();
        let cfg = std::fs::read_to_string(tmp.path().join(".saddle/vite.config.mts")).unwrap();
        // Should NOT try to import a non-existent file
        assert!(!cfg.contains("import userConfig from"), "expected no userConfig import; got: {cfg}");
        // Should still wire saddlePlugin
        assert!(cfg.contains("saddlePlugin()"));
        // Should resolve to an empty config object
        assert!(cfg.contains("const config = {};"));
    }

    #[test]
    fn handles_paths_with_spaces() {
        let tmp = TempDir::new().unwrap();
        let spaced = tmp.path().join("project with spaces");
        std::fs::create_dir_all(&spaced).unwrap();
        std::fs::write(spaced.join("vite.config.ts"), "export default {};").unwrap();

        write_saddle_runtime(
            spaced.to_str().unwrap(),
            Some(spaced.join("vite.config.ts").to_str().unwrap()),
        ).unwrap();

        let cfg = std::fs::read_to_string(spaced.join(".saddle/vite.config.mts")).unwrap();
        // The import path should be a properly-quoted JS string literal (serde_json output).
        assert!(cfg.contains(r#"import userConfig from "../vite.config.ts""#),
            "expected JSON-encoded import path; got: {cfg}");
    }

    #[test]
    fn appends_gitignore_idempotently() {
        let tmp = TempDir::new().unwrap();
        std::fs::write(tmp.path().join(".gitignore"), "node_modules\n").unwrap();

        write_saddle_runtime(tmp.path().to_str().unwrap(), None).unwrap();
        write_saddle_runtime(tmp.path().to_str().unwrap(), None).unwrap();

        let gi = std::fs::read_to_string(tmp.path().join(".gitignore")).unwrap();
        let count = gi.lines().filter(|l| l.trim() == ".saddle/").count();
        assert_eq!(count, 1, "should only append once across multiple runs");
    }

    #[test]
    fn creates_gitignore_if_missing() {
        let tmp = TempDir::new().unwrap();
        write_saddle_runtime(tmp.path().to_str().unwrap(), None).unwrap();
        let gi = std::fs::read_to_string(tmp.path().join(".gitignore")).unwrap();
        assert_eq!(gi.trim(), ".saddle/");
    }
}
