use std::path::Path;

const VITE_CONFIG_TEMPLATE: &str = r#"// Generated by Saddle. Do not edit — regenerated on every project load.
import { defineConfig, loadEnv } from 'vite';
import saddlePlugin from './saddle-plugin.mjs';

export default defineConfig(async (env) => {
  let userConfig: any = {};
  try {
    const mod = await import('__USER_CONFIG_IMPORT__');
    const exported = mod.default ?? mod;
    userConfig = typeof exported === 'function' ? await exported(env) : exported;
  } catch (err) {
    console.warn('[saddle] no user vite.config detected; running with empty base config');
  }
  return {
    ...userConfig,
    plugins: [...(userConfig.plugins ?? []), saddlePlugin()],
  };
});
"#;

const SADDLE_PLUGIN_TEMPLATE: &str = r#"// Generated by Saddle. Do not edit — regenerated on every project load.
const VIRTUAL_ID = 'virtual:saddle-bridge';
const RESOLVED_ID = '\0' + VIRTUAL_ID;
const BRIDGE_SOURCE = __BRIDGE_SOURCE__;

export default function saddlePlugin() {
  return {
    name: 'saddle',
    enforce: 'pre',
    resolveId(id) { if (id === VIRTUAL_ID) return RESOLVED_ID; },
    load(id) { if (id === RESOLVED_ID) return BRIDGE_SOURCE; },
    transformIndexHtml(html) {
      return html.replace(
        /<\/head>/i,
        `<script type="module" src="/@id/${VIRTUAL_ID}"></script></head>`
      );
    },
  };
}
"#;

const BRIDGE_SOURCE: &str = include_str!("../../saddle-bridge.js");

pub fn write_saddle_runtime(project_root: &str, vite_config_path: Option<&str>) -> Result<(), String> {
    let root = Path::new(project_root);
    let saddle_dir = root.join(".saddle");
    std::fs::create_dir_all(&saddle_dir).map_err(|e| format!("create .saddle: {e}"))?;

    // vite.config.mts wrapper. Compute the relative import path to the user's config.
    let import_path = match vite_config_path {
        Some(p) => {
            let rel = Path::new(p)
                .strip_prefix(root)
                .map_err(|e| format!("path strip: {e}"))?;
            // Vite imports need a leading ../ from .saddle/
            format!("../{}", rel.display())
        }
        None => "../vite.config.ts".to_string(), // fallback; the import will fail and we log a warning
    };

    let vite_config_contents = VITE_CONFIG_TEMPLATE.replace("__USER_CONFIG_IMPORT__", &import_path);
    std::fs::write(saddle_dir.join("vite.config.mts"), vite_config_contents)
        .map_err(|e| format!("write vite.config.mts: {e}"))?;

    // saddle-plugin.mjs: inline the bridge as a JSON string literal so escaping is correct.
    let bridge_literal = serde_json::to_string(BRIDGE_SOURCE).map_err(|e| format!("encode bridge: {e}"))?;
    let plugin_contents = SADDLE_PLUGIN_TEMPLATE.replace("__BRIDGE_SOURCE__", &bridge_literal);
    std::fs::write(saddle_dir.join("saddle-plugin.mjs"), plugin_contents)
        .map_err(|e| format!("write saddle-plugin.mjs: {e}"))?;

    // .gitignore: append `.saddle/` if not already present. Create file if missing.
    let gitignore = root.join(".gitignore");
    let current = std::fs::read_to_string(&gitignore).unwrap_or_default();
    if !current.lines().any(|l| l.trim() == ".saddle" || l.trim() == ".saddle/") {
        let new_contents = if current.is_empty() {
            ".saddle/\n".to_string()
        } else if current.ends_with('\n') {
            format!("{current}.saddle/\n")
        } else {
            format!("{current}\n.saddle/\n")
        };
        std::fs::write(&gitignore, new_contents).map_err(|e| format!("write .gitignore: {e}"))?;
    }

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::TempDir;

    #[test]
    fn writes_saddle_dir_files() {
        let tmp = TempDir::new().unwrap();
        std::fs::write(tmp.path().join("vite.config.ts"), "export default {};").unwrap();

        write_saddle_runtime(
            tmp.path().to_str().unwrap(),
            Some(tmp.path().join("vite.config.ts").to_str().unwrap()),
        ).unwrap();

        let cfg = std::fs::read_to_string(tmp.path().join(".saddle/vite.config.mts")).unwrap();
        assert!(cfg.contains("../vite.config.ts"));

        let plugin = std::fs::read_to_string(tmp.path().join(".saddle/saddle-plugin.mjs")).unwrap();
        assert!(plugin.contains("virtual:saddle-bridge"));
        // The bridge contents got inlined as a JSON string.
        assert!(plugin.contains("__SADDLE_BRIDGE_INSTALLED__"));
    }

    #[test]
    fn appends_gitignore_idempotently() {
        let tmp = TempDir::new().unwrap();
        std::fs::write(tmp.path().join(".gitignore"), "node_modules\n").unwrap();

        write_saddle_runtime(tmp.path().to_str().unwrap(), None).unwrap();
        write_saddle_runtime(tmp.path().to_str().unwrap(), None).unwrap();

        let gi = std::fs::read_to_string(tmp.path().join(".gitignore")).unwrap();
        let count = gi.lines().filter(|l| l.trim() == ".saddle/").count();
        assert_eq!(count, 1, "should only append once across multiple runs");
    }

    #[test]
    fn creates_gitignore_if_missing() {
        let tmp = TempDir::new().unwrap();
        write_saddle_runtime(tmp.path().to_str().unwrap(), None).unwrap();
        let gi = std::fs::read_to_string(tmp.path().join(".gitignore")).unwrap();
        assert_eq!(gi.trim(), ".saddle/");
    }
}
